"""empty message

Revision ID: 0f66beff93a9
Revises: d6e950eaaa13
Create Date: 2024-05-05 15:59:21.762588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f66beff93a9'
down_revision = 'd6e950eaaa13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('departure_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('arrival_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('start_station', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('end_station', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=15), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('end_station')
        batch_op.drop_column('start_station')
        batch_op.drop_column('arrival_date')
        batch_op.drop_column('departure_date')

    # ### end Alembic commands ###
