"""empty message

Revision ID: 58737085f116
Revises: 
Create Date: 2024-05-19 20:17:50.915981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58737085f116'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('promotion_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_ticket_promotion_id'), ['promotion_id'], unique=False)
        batch_op.create_foreign_key('fk_ticket_promotion', 'promotion', ['promotion_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_ticket_promotion_id'))
        batch_op.drop_column('promotion_id')

    # ### end Alembic commands ###
