"""empty message

Revision ID: 86d4b169a68c
Revises: 58737085f116
Create Date: 2024-05-19 20:22:56.634030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86d4b169a68c'
down_revision = '58737085f116'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.alter_column('promotion_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.alter_column('promotion_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
