"""empty message

Revision ID: 88c74cbdd369
Revises: b500d2b08df6
Create Date: 2024-05-30 18:38:44.738253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88c74cbdd369'
down_revision = 'b500d2b08df6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('section', schema=None) as batch_op:
        batch_op.add_column(sa.Column('train_name', sa.String(length=50), nullable=True))
        batch_op.drop_column('train_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('section', schema=None) as batch_op:
        batch_op.add_column(sa.Column('train_id', sa.INTEGER(), nullable=True))
        batch_op.drop_column('train_name')

    # ### end Alembic commands ###
