"""empty message

Revision ID: b500d2b08df6
Revises: 933aa3732dba
Create Date: 2024-05-30 18:28:31.563316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b500d2b08df6'
down_revision = '933aa3732dba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_price', sa.Float(precision=10), nullable=False))
        batch_op.drop_column('end_station')
        batch_op.drop_column('start_station')
        batch_op.drop_column('arrival_date')
        batch_op.drop_column('price')
        batch_op.drop_column('departure_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('departure_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('price', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('arrival_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('start_station', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('end_station', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('total_price')

    # ### end Alembic commands ###
