"""users table

Revision ID: 840fa37599a1
Revises: 62f56ca846ca
Create Date: 2024-05-09 17:53:40.144681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '840fa37599a1'
down_revision = '62f56ca846ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stationplan', schema=None) as batch_op:
        batch_op.drop_index('ix_stationplan_endstation')
        batch_op.create_index(batch_op.f('ix_stationplan_endstation'), ['endstation'], unique=False)
        batch_op.drop_index('ix_stationplan_price')
        batch_op.create_index(batch_op.f('ix_stationplan_price'), ['price'], unique=False)
        batch_op.drop_index('ix_stationplan_startstation')
        batch_op.create_index(batch_op.f('ix_stationplan_startstation'), ['startstation'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stationplan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stationplan_startstation'))
        batch_op.create_index('ix_stationplan_startstation', ['startstation'], unique=1)
        batch_op.drop_index(batch_op.f('ix_stationplan_price'))
        batch_op.create_index('ix_stationplan_price', ['price'], unique=1)
        batch_op.drop_index(batch_op.f('ix_stationplan_endstation'))
        batch_op.create_index('ix_stationplan_endstation', ['endstation'], unique=1)

    # ### end Alembic commands ###
