"""users table

Revision ID: a47b68be3b72
Revises: a51b1b31c06e
Create Date: 2024-05-08 16:41:12.155706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a47b68be3b72'
down_revision = 'a51b1b31c06e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('railcar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('track_width', sa.Integer(), nullable=False),
    sa.Column('max_tensile_fore', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('railcar', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_railcar_user_id'), ['user_id'], unique=False)

    op.drop_table('followers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.INTEGER(), nullable=False),
    sa.Column('followed_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    with op.batch_alter_table('railcar', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_railcar_user_id'))

    op.drop_table('railcar')
    # ### end Alembic commands ###
