"""Added max_tensile_force to Railcar

Revision ID: cec6d0a06f1d
Revises: a47b68be3b72
Create Date: 2024-05-08 18:41:56.232743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cec6d0a06f1d'
down_revision = 'a47b68be3b72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('railcar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_tensile_force', sa.Float(precision=10), nullable=False))
        batch_op.alter_column('track_width',
               existing_type=sa.INTEGER(),
               type_=sa.Float(precision=10),
               existing_nullable=False)
        batch_op.drop_column('max_tensile_fore')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('railcar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_tensile_fore', sa.INTEGER(), nullable=False))
        batch_op.alter_column('track_width',
               existing_type=sa.Float(precision=10),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('max_tensile_force')

    # ### end Alembic commands ###
